### PR TITLE
BasicPHP class library

### PR DESCRIPTION
**Pull request by ray-ang**
BasicPHP is a class library that can be used for development without the use of frameworks.

### CODE REVIEW

**Comment by AlessandroMinoccheri** [comment]
Thanks for your contribution @ray-ang .
why do you think it is right to add it to this repo?
Because IMHO your library is like a framework so I don't think that can add value to this repository.

The main focus of this repo should be to create awareness on the decoupling domain from the framework for example not to create libraries or other frameworks. 

Let me know what do you think and we can try to understand together the right way :)

**Comment by ray-ang** [comment]
Greetings, @AlessandroMinoccheri .
The BasicPHP github repository does have a lot of files in it since I integrated a sample site for the library, but the library itself is just one file/class - Basic.php.

The main reason why it is a library promoting the frameworkless movement is because the codes inside the methods are all native/built-in PHP functions. There is no dependency to any other packages/frameworks where codes inside the methods are abstractions based on dependencies.

To illustrate, I am using the BasicPHP class library to provide encryption functionality to a WordPress plugin I am working on at https://github.com/ray-ang/open-nis-patient-care-summary. In this repo, the class library is included in the script, and only the encryption functionalities of the class library are used.

I have also tried simply including the class library on top of the front controller script of PHP frameworks, and it is possible to decouple the logic created using BasicPHP methods with executions of the framework just by including the class library on top of the front controller script.

BasicPHP illustrates the importance of libraries created using native/built-in functions of a particular programming language so that it is easy to decouple functionalities, and the code becomes portable.

**Comment by ray-ang** [comment]
Hello, @AlessandroMinoccheri .

I updated the BasicPHP repo folder structure to illustrate the purpose of the library approach of using PHP native/built-in functions to design applications and API's without frameworks or dependencies, thereby, ensuring decoupling of the code base and making it portable.

Regards,
Raymund

**Comment by AlessandroMinoccheri** [comment]
Hello @ray-ang I have seen your update on BasicPHP but I think that it's a little bit different from the scope of `awesome-frameworkless` 
I really appreciate your work but in this case, IMHO it shouldn't be added to this repository.
If you want, you can try to write an article about your work and how it can help other developers without using a framework.
The important for me it's not to have a library that helps me, but the approach.

**Comment by ray-ang** [comment]
Greetings @AlessandroMinoccheri . I will probably concentrate on the frameworkless approach, like creating an article on BasicPHP or further exploring what a framework is, since the repository does not deal with libraries.

I also browsed through the manifesto definition of what a framework is, and one of the definition is "A library that invokes your code and gives to you a structure". Since BasicPHP is a class library with methods that can be invoked, it would qualify as a sort of a framework based on the manifesto's definition.

With this, I would like to ask what is the Frameworkless Movement's stand on the use of package managers, like composer? Since packages can mostly be considered libraries with defined structure on doing things, which could be done using native programming language functions? When can it be considered frameworkless when using composer?

Thanks!

**Pull request closed without merging**
