### PR TITLE
Add article

### PR DESCRIPTION
**Pull request by andreoss**
- Add a 2005 article by Benji Smith as it seems to be on topic, initially found on http://harmful.cat-v.org/software/

### CODE REVIEW

**Comment by xpmatteo** [comment]
The article is a classic!  However, I think it's not really about frameworks; it's about needless complexity in general, and about the way Java development was intended at the time, by framework and library authors.  It is amusing, yes, and it does not give you any positive advice.

**Comment by andreoss** [comment]
Okay, closing than

**Comment by xpmatteo** [comment]
That was just my opinion.  Let's hear what other contributors think!

**Comment by AlessandroMinoccheri** [comment]
I agree with @xpmatteo but thanks for your contribution.

**Pull request closed without merging**
